from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class OneKeyAssets: 


	# Image Rule Assets
	# 安全点击 
	I_OK_SAFE = RuleImage(roi_front=(614,67,100,68), roi_back=(614,67,100,68), threshold=0.8, method="Template matching", file="./tasks/OneKey/ok/ok_ok_safe.png")
	# 第一页 
	I_OK_C1 = RuleImage(roi_front=(1124,585,100,68), roi_back=(1124,585,100,68), threshold=0.8, method="Template matching", file="./tasks/OneKey/ok/ok_ok_c1.png")
	# 第二页 
	I_OK_C2 = RuleImage(roi_front=(236,53,824,100), roi_back=(236,53,824,100), threshold=0.8, method="Template matching", file="./tasks/OneKey/ok/ok_ok_c2.png")
	# 第三页 
	I_OK_C3 = RuleImage(roi_front=(0,0,100,100), roi_back=(0,0,100,100), threshold=0.8, method="Template matching", file="./tasks/OneKey/ok/ok_ok_c3.png")


	# Image Rule Assets
	# 御魂溢出 
	I_OVER_GHOST = RuleImage(roi_front=(609,410,65,28), roi_back=(609,410,65,28), threshold=0.8, method="Template matching", file="./tasks/OneKey/ok/ok_over_ghost.png")
	# 第一页 
	I_OK_I1 = RuleImage(roi_front=(1125,599,100,47), roi_back=(1125,599,100,47), threshold=0.8, method="Template matching", file="./tasks/OneKey/ok/ok_ok_i1.png")
	# 第二页 
	I_OK_I2 = RuleImage(roi_front=(166,643,26,21), roi_back=(166,643,26,21), threshold=0.8, method="Template matching", file="./tasks/OneKey/ok/ok_ok_i2.png")
	# 第三页 
	I_OK_I3 = RuleImage(roi_front=(0,0,100,100), roi_back=(0,0,100,100), threshold=0.8, method="Template matching", file="./tasks/OneKey/ok/ok_ok_i3.png")


