from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class OneKeyAssets: 


	# Image Rule Assets
	# 第一页 
	I_OK_1 = RuleImage(roi_front=(1121,579,100,100), roi_back=(1121,579,100,100), threshold=0.8, method="Template matching", file="./tasks/OneKey/ok/ok_ok_1.png")
	# 第二页 
	I_OK_2 = RuleImage(roi_front=(236,53,824,100), roi_back=(236,53,824,100), threshold=0.8, method="Template matching", file="./tasks/OneKey/ok/ok_ok_2.png")
	# 第三页 
	I_OK_3 = RuleImage(roi_front=(0,0,100,100), roi_back=(0,0,100,100), threshold=0.8, method="Template matching", file="./tasks/OneKey/ok/ok_ok_3.png")


	# Image Rule Assets
	# 御魂溢出 
	I_OVER_GHOST = RuleImage(roi_front=(609,410,65,28), roi_back=(609,410,65,28), threshold=0.8, method="Template matching", file="./tasks/OneKey/ok/ok_over_ghost.png")
	# 第一页 
	I_OK_1 = RuleImage(roi_front=(1122,591,100,47), roi_back=(1122,591,100,47), threshold=0.8, method="Template matching", file="./tasks/OneKey/ok/ok_ok_1.png")
	# 第二页 
	I_OK_2 = RuleImage(roi_front=(14,97,100,32), roi_back=(14,97,100,32), threshold=0.8, method="Template matching", file="./tasks/OneKey/ok/ok_ok_2.png")
	# 第三页 
	I_OK_3 = RuleImage(roi_front=(0,0,100,100), roi_back=(0,0,100,100), threshold=0.8, method="Template matching", file="./tasks/OneKey/ok/ok_ok_3.png")


