from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class ActivityShikigamiAssets: 


	# Click Rule Assets
	# description 
	C_RANDOM_LEFT = RuleClick(roi_front=(17,84,104,356), roi_back=(17,81,106,365), name="random_left")
	# description 
	C_RANDOM_RIGHT = RuleClick(roi_front=(1133,88,131,361), roi_back=(1131,84,133,363), name="random_right")
	# description 
	C_RANDOM_TOP = RuleClick(roi_front=(126,66,989,58), roi_back=(123,65,991,58), name="random_top")
	# description 
	C_RANDOM_BOTTOM = RuleClick(roi_front=(196,598,581,78), roi_back=(194,597,583,81), name="random_bottom")
	# description 
	C_RANDOM_ALL = RuleClick(roi_front=(42,94,1207,543), roi_back=(42,94,1207,543), name="random_all")


	# Image Rule Assets
	# 上锁图标 
	I_LOCK = RuleImage(roi_front=(911,645,21,23), roi_back=(685,612,330,86), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/as/as_lock.png")
	# 还未上锁图片 
	I_UNLOCK = RuleImage(roi_front=(884,648,28,25), roi_back=(686,610,313,92), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/as/as_unlock.png")
	# 活动爬塔标志 
	I_CLIMB_MODE_PASS = RuleImage(roi_front=(1141,544,21,21), roi_back=(1118,510,119,186), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_climb_mode_pass.png")
	# 体力爬塔标志 
	I_CLIMB_MODE_AP = RuleImage(roi_front=(1163,544,22,25), roi_back=(1055,495,202,219), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_climb_mode_ap.png")
	# 切换按键 
	I_CLIMB_MODE_SWITCH = RuleImage(roi_front=(1232,545,29,26), roi_back=(1174,511,104,82), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_climb_mode_switch.png")
	# 100体爬塔标志 
	I_CLIMB_MODE_AP100 = RuleImage(roi_front=(1186,665,22,25), roi_back=(1055,495,202,219), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_climb_mode_ap100.png")
	# 体力爬塔阵容解锁 
	I_AP_UNLOCK = RuleImage(roi_front=(788,656,22,25), roi_back=(686,610,313,92), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_ap_unlock.png")
	# 体力爬塔阵容锁定 
	I_AP_LOCK = RuleImage(roi_front=(788,656,22,25), roi_back=(686,610,313,92), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_ap_lock.png")
	# 活动通用挑战图标 
	I_ACT_FIRE = RuleImage(roi_front=(1132,602,84,45), roi_back=(1080,530,192,190), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_act_fire.png")
	# boss挑战标志 
	I_AS_BOSS_FIRE = RuleImage(roi_front=(1130,590,92,47), roi_back=(1080,530,192,190), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_as_boss_fire.png")


	# Image Rule Assets
	# 买门票 
	I_RM_BUY_TICKET = RuleImage(roi_front=(873,472,95,44), roi_back=(843,456,149,75), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_rm_buy_ticket.png")
	# 买奖励 
	I_RM_BUY_REWARD = RuleImage(roi_front=(586,475,99,39), roi_back=(559,454,150,79), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_rm_buy_reward.png")
	# 买体力 
	I_RM_BUY_AP = RuleImage(roi_front=(312,472,94,41), roi_back=(283,459,148,71), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_rm_buy_ap.png")
	# 投掷骰子 
	I_RM_THROW = RuleImage(roi_front=(1063,554,80,29), roi_back=(1012,445,183,196), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_rm_throw.png")
	# 投掷对决开始 
	I_RM_CHECK_THROW = RuleImage(roi_front=(606,337,76,87), roi_back=(531,253,238,249), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_rm_check_throw.png")
	# 投掷胜利 
	I_RM_THROW_WIN = RuleImage(roi_front=(667,317,65,80), roi_back=(608,261,189,186), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_rm_throw_win.png")
	# 问答 
	I_RM_QUESTION = RuleImage(roi_front=(541,109,212,40), roi_back=(482,30,339,171), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_rm_question.png")
	#  
	I_RM_FORWARD = RuleImage(roi_front=(550,495,91,43), roi_back=(515,474,161,100), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_rm_forward.png")
	# 扔骰子平局 
	I_RM_THROW_EQUAL = RuleImage(roi_front=(350,355,51,75), roi_back=(277,307,189,186), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_rm_throw_equal.png")
	#  
	I_RM_BOSS = RuleImage(roi_front=(595,75,95,44), roi_back=(569,61,149,75), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_rm_boss.png")
	#  
	I_RM_NO_TICKET = RuleImage(roi_front=(356,113,95,44), roi_back=(322,82,167,102), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_rm_no_ticket.png")


	# Ocr Rule Assets
	# 挑战 
	O_FIRE = RuleOcr(roi=(962,529,308,171), area=(964,530,309,171), mode="Full", method="Default", keyword="挑战", name="fire")
	# 体力的数量检测 
	O_REMAIN_AP = RuleOcr(roi=(748,14,95,34), area=(748,14,95,34), mode="DigitCounter", method="Default", keyword="", name="remain_ap")
	# 活动体力的剩余检测 
	O_REMAIN_PASS = RuleOcr(roi=(563,15,88,31), area=(563,15,88,31), mode="DigitCounter", method="Default", keyword="", name="remain_pass")
	# 还有多少次购买体力的机会 
	O_REMAIN_BUY = RuleOcr(roi=(808,531,39,42), area=(808,531,39,42), mode="DigitCounter", method="Default", keyword="", name="remain_buy")
	# 活动票数（没有百分比） 
	O_REMAIN_PASS2 = RuleOcr(roi=(750,17,88,29), area=(750,17,88,29), mode="Digit", method="Default", keyword="", name="remain_pass2")
	# boss剩余攻击次数 
	O_REMAIN_BOSS = RuleOcr(roi=(1169,668,70,30), area=(1169,668,70,30), mode="DigitCounter", method="Default", keyword="", name="remain_boss")
	# 100体活动门票检测 
	O_REMAIN_AP100 = RuleOcr(roi=(922,21,112,39), area=(913,8,131,62), mode="Digit", method="Default", keyword="", name="remain_ap100")
	# 进入100体活动标识 
	O_ENTER_AP100 = RuleOcr(roi=(67,99,92,359), area=(67,99,92,359), mode="Full", method="Default", keyword="雪山修行", name="enter_ap100")


	# Ocr Rule Assets
	#  
	O_RM_QUESTION = RuleOcr(roi=(358,159,593,111), area=(358,159,593,111), mode="Full", method="Default", keyword="", name="rm_question")
	#  
	O_RM_ANSWER_1 = RuleOcr(roi=(415,290,468,53), area=(415,290,468,53), mode="Single", method="Default", keyword="", name="rm_answer_1")
	#  
	O_RM_ANSWER_2 = RuleOcr(roi=(418,401,467,53), area=(418,401,467,53), mode="Single", method="Default", keyword="", name="rm_answer_2")
	#  
	O_RM_ANSWER_3 = RuleOcr(roi=(418,516,468,54), area=(418,516,468,54), mode="Single", method="Default", keyword="", name="rm_answer_3")


	# Image Rule Assets
	# 庭院进入活动 
	I_MAIN_GOTO_ACT = RuleImage(roi_front=(1190,300,35,28), roi_back=(1164,134,83,393), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/as/as_main_goto_act.png")
	# 右上跳过按钮 
	I_SKIP_BUTTON = RuleImage(roi_front=(1159,37,51,22), roi_back=(1141,27,86,43), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_skip_button.png")
	# 进入主要的战斗界面 
	I_TO_BATTLE_MAIN = RuleImage(roi_front=(242,289,39,139), roi_back=(209,170,155,370), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_to_battle_main.png")
	# 点击进入boss战斗页面 
	I_TO_BATTLE_BOSS = RuleImage(roi_front=(935,250,35,123), roi_back=(876,165,234,327), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_to_battle_boss.png")
	# boss界面标志 
	I_CHECK_BATTLE_BOSS = RuleImage(roi_front=(151,18,129,46), roi_back=(141,0,151,85), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_check_battle_boss.png")
	# 从main进入到式神录 
	I_BATTLE_MAIN_TO_RECORDS = RuleImage(roi_front=(1015,560,39,42), roi_back=(674,539,439,157), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_battle_main_to_records.png")
	# 进入门票活动的按钮 
	I_AS_TO_PASS = RuleImage(roi_front=(624,505,38,35), roi_back=(273,141,759,475), threshold=0.65, method="Template matching", file="./tasks/ActivityShikigami/as/as_as_to_pass.png")
	# 确认跳过 
	I_CONFIRM_SKIP = RuleImage(roi_front=(707,442,137,38), roi_back=(656,397,231,124), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_confirm_skip.png")
	#  
	I_RM_CHECK_BOSS = RuleImage(roi_front=(988,599,75,29), roi_back=(952,546,142,115), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_rm_check_boss.png")
	# 活动页2标志 
	I_AS_CHECK_MAIN_2 = RuleImage(roi_front=(566,10,151,36), roi_back=(505,0,256,92), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_as_check_main_2.png")
	# 打开眼睛按钮 
	I_AS_OPEN_EYE = RuleImage(roi_front=(1198,300,60,54), roi_back=(1146,253,134,217), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_as_open_eye.png")
	# 活动定位按钮 
	I_AS_LOCATE = RuleImage(roi_front=(1212,394,34,36), roi_back=(1146,253,134,217), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_as_locate.png")
	# 关闭眼睛按钮 
	I_AS_CLOSE_EYE = RuleImage(roi_front=(1197,297,63,57), roi_back=(1146,253,134,217), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_as_close_eye.png")
	# 活动主界面进入体力爬塔标志 
	I_TO_BATTLE_AP = RuleImage(roi_front=(825,321,39,139), roi_back=(720,255,238,269), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_to_battle_ap.png")


