from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class EternitySeaAssets: 


	# Image Rule Assets
	# 选择永生之海 
	I_ETERNITY_SEA = RuleImage(roi_front=(1172,98,50,109), roi_back=(1054,88,180,244), threshold=0.8, method="Template matching", file="./tasks/EternitySea/res/res_eternity_sea.png")
	# 组队 
	I_FORM_TEAM = RuleImage(roi_front=(964,603,89,51), roi_back=(931,558,165,162), threshold=0.8, method="Template matching", file="./tasks/EternitySea/res/res_form_team.png")
	# 挑战 
	I_ETERNITY_SEA_FIRE = RuleImage(roi_front=(1142,596,93,48), roi_back=(1102,556,171,164), threshold=0.8, method="Template matching", file="./tasks/EternitySea/res/res_eternity_sea_fire.png")
	# 开锁 
	I_ETERNITYSEA_UNLOCK = RuleImage(roi_front=(705,659,20,26), roi_back=(645,630,195,90), threshold=0.8, method="Template matching", file="./tasks/EternitySea/res/res_eternitysea_unlock.png")
	# 关锁 
	I_NEWETERNITYSEA_LOCK = RuleImage(roi_front=(702,658,24,28), roi_back=(655,636,182,84), threshold=0.6, method="Template matching", file="./tasks/EternitySea/res/res_neweternitysea_lock.png")


	# List Rule Assets
	# 永生之海层数列表 
	L_LAYER_LIST = RuleList(folder="./tasks/EternitySea/res", direction="vertical", mode="ocr", roi_back=(128,103,62,586), size=(62, 107), 
					 array=["壹", "贰", "叁", "肆"])


