from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class ChessAssets:


	# Click Rule Assets
	# 商店式神5
	C_SHIKIGAMI_5 = RuleClick(roi_front=(350,61,167,140), roi_back=(350,61,167,140), name="shikigami_5")
	# 商店式神4
	C_SHIKIGAMI_4 = RuleClick(roi_front=(537,61,167,140), roi_back=(537,61,167,140), name="shikigami_4")
	# 商店式神3
	C_SHIKIGAMI_3 = RuleClick(roi_front=(724,61,167,140), roi_back=(724,61,167,140), name="shikigami_3")
	# 商店式神2
	C_SHIKIGAMI_2 = RuleClick(roi_front=(911,61,167,140), roi_back=(911,61,167,140), name="shikigami_2")
	# 商店式神1
	C_SHIKIGAMI_1 = RuleClick(roi_front=(1098,61,167,140), roi_back=(1098,61,167,140), name="shikigami_1")
	#
	C_SHIKIGAMI_STORE = RuleClick(roi_front=(344,55,925,241), roi_back=(344,55,925,241), name="shikigami_store")
	# 左侧符咒选项卡面
	C_GRIGRI_OPTION_1 = RuleClick(roi_front=(320,205,90,130), roi_back=(320,205,90,130), name="grigri_option_1")
	# 中间符咒选项卡面
	C_GRIGRI_OPTION_2 = RuleClick(roi_front=(598,205,90,130), roi_back=(598,205,90,130), name="grigri_option_2")
	# 右侧符咒选项卡面
	C_GRIGRI_OPTION_3 = RuleClick(roi_front=(875,205,90,130), roi_back=(875,205,90,130), name="grigri_option_3")
	# 左侧符咒刷新
	C_GRIGRI_REFRESH_1 = RuleClick(roi_front=(300,600,122,40), roi_back=(300,600,122,40), name="grigri_refresh_1")
	# 中间符咒刷新
	C_GRIGRI_REFRESH_2 = RuleClick(roi_front=(587,596,122,40), roi_back=(587,596,122,40), name="grigri_refresh_2")
	# 右侧符咒刷新
	C_GRIGRI_REFRESH_3 = RuleClick(roi_front=(862,599,122,40), roi_back=(862,599,122,40), name="grigri_refresh_3")
	# 关闭式神详情界面
	C_CLICK_CLOSE_SPECIFICS_AREA = RuleClick(roi_front=(193,95,91,430), roi_back=(193,95,91,430), name="click_close_specifics_area")
	# 取消匹配等待
	C_CANCEL_WAITING = RuleClick(roi_front=(584,597,111,45), roi_back=(579,592,121,55), name="cancel_waiting")


	# Image Rule Assets
	# 选符咒环节
	I_SELECT_GRIGRI = RuleImage(roi_front=(533,74,218,43), roi_back=(533,74,218,43), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_select_grigri.png")
	#
	I_CHESS_START = RuleImage(roi_front=(1159,595,65,66), roi_back=(1150,585,85,86), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_chess_start.png")
	#
	I_USE_SOUL = RuleImage(roi_front=(1005,144,172,47), roi_back=(1000,139,182,57), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_use_soul.png")
	#
	I_SELECT_SOUL_1 = RuleImage(roi_front=(390,326,70,35), roi_back=(385,321,80,45), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_select_soul_1.png")
	#
	I_SELECT_SOUL_2 = RuleImage(roi_front=(605,326,70,35), roi_back=(600,321,80,45), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_select_soul_2.png")
	#
	I_SELECT_SOUL_3 = RuleImage(roi_front=(821,327,70,35), roi_back=(816,322,80,45), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_select_soul_3.png")
	# 商店
	I_MARKET = RuleImage(roi_front=(1159,614,89,26), roi_back=(1154,609,99,36), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_market.png")
	# 购买经验
	I_EXPERIENCE = RuleImage(roi_front=(37,641,102,26), roi_back=(32,636,112,36), threshold=0.7, method="Template matching", file="./tasks/Chess/c/c_experience.png")
	# 打开阵容预设
	I_OPEN_LINEUP = RuleImage(roi_front=(271,17,33,34), roi_back=(259,7,57,53), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_open_lineup.png")
	# 商店刷新
	I_REFRESH = RuleImage(roi_front=(1169,419,65,64), roi_back=(1159,409,85,84), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_refresh.png")
	#
	I_REFRESH_NOT_GOLD = RuleImage(roi_front=(1169,419,65,64), roi_back=(1164,414,75,74), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_refresh_not_gold.png")
	#
	I_SKIP = RuleImage(roi_front=(1148,39,77,22), roi_back=(1143,34,87,32), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_skip.png")
	#
	I_SHIKIGAMI_SPECIFICS = RuleImage(roi_front=(939,223,310,32), roi_back=(939,223,310,32), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_shikigami_specifics.png")
	#
	I_CHECK_MARKET = RuleImage(roi_front=(1206,319,35,31), roi_back=(1201,314,45,41), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_check_market.png")
	#
	I_CANCEL_WAITING = RuleImage(roi_front=(584,597,111,45), roi_back=(579,592,121,55), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_cancel_waiting.png")
	#
	I_GAME_OVER_1 = RuleImage(roi_front=(549,401,198,31), roi_back=(544,396,208,41), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_game_over_1.png")
	#
	I_GAME_OVER_2 = RuleImage(roi_front=(549,401,198,31), roi_back=(544,396,208,41), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_game_over_2.png")
	#
	I_GRIGRI_GOLD = RuleImage(roi_front=(584,142,122,40), roi_back=(579,137,132,50), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_grigri_gold.png")
	#
	I_GRIGRI_SILVER = RuleImage(roi_front=(584,142,122,40), roi_back=(579,137,132,50), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_grigri_silver.png")
	#
	I_GRIGRI_COPPER = RuleImage(roi_front=(584,142,122,40), roi_back=(579,137,132,50), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_grigri_copper.png")
	#
	I_CHECK_GOLDFISH = RuleImage(roi_front=(924,291,192,49), roi_back=(919,286,202,59), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_check_goldfish.png")
	#
	I_BACK_RED = RuleImage(roi_front=(977,67,41,46), roi_back=(972,62,51,56), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_back_red.png")
	#
	I_QUESTION_CHECK = RuleImage(roi_front=(209,16,33,34), roi_back=(199,5,57,53), threshold=0.8, method="Template matching", file="./tasks/Chess/c/c_question_check.png")


	# Ocr Rule Assets
	# 商店式神名称5
	O_SHIKIGAMI_GOLD_5 = RuleOcr(roi=(481,266,38,24), area=(481,266,38,24), mode="Digit", method="Default", keyword="", name="shikigami_gold_5")
	# 商店式神名称4
	O_SHIKIGAMI_GOLD_4 = RuleOcr(roi=(668,266,38,24), area=(668,266,38,24), mode="Digit", method="Default", keyword="", name="shikigami_gold_4")
	# 商店式神名称3
	O_SHIKIGAMI_GOLD_3 = RuleOcr(roi=(855,266,38,24), area=(855,266,38,24), mode="Digit", method="Default", keyword="", name="shikigami_gold_3")
	# 商店式神名称2
	O_SHIKIGAMI_GOLD_2 = RuleOcr(roi=(1042,266,38,24), area=(1042,266,38,24), mode="Digit", method="Default", keyword="", name="shikigami_gold_2")
	# 商店式神名称1
	O_SHIKIGAMI_GOLD_1 = RuleOcr(roi=(1229,266,38,24), area=(1229,266,38,24), mode="Digit", method="Default", keyword="", name="shikigami_gold_1")
	# 当前等级
	O_LEVEL = RuleOcr(roi=(128,678,53,34), area=(128,678,53,34), mode="Single", method="Default", keyword="", name="level")
	# 当前回目
	O_ROUND = RuleOcr(roi=(469,0,67,30), area=(469,0,67,30), mode="Single", method="Default", keyword="", name="round")
	# 当前金币
	O_GOLD = RuleOcr(roi=(1198,640,43,32), area=(1198,640,43,32), mode="Digit", method="Default", keyword="", name="gold")
	# 当前环节
	O_CHESS_MODE = RuleOcr(roi=(741,0,32,28), area=(741,0,32,28), mode="Single", method="Default", keyword="", name="chess_mode")
	#
	O_ROUND_2 = RuleOcr(roi=(507,0,62,30), area=(507,0,62,30), mode="Single", method="Default", keyword="", name="round_2")
	#
	O_CHESS_MODE_2 = RuleOcr(roi=(706,2,32,28), area=(706,2,32,28), mode="Single", method="Default", keyword="", name="chess_mode_2")
	#
	O_BADGE_AREA = RuleOcr(roi=(181,650,945,46), area=(181,650,945,46), mode="Single", method="Default", keyword="", name="badge_area")
	#
	O_COIN = RuleOcr(roi=(141,659,87,25), area=(141,659,87,25), mode="DigitCounter", method="Default", keyword="", name="coin")
	#
	O_NOW_TIME = RuleOcr(roi=(768,0,32,28), area=(768,0,32,28), mode="Single", method="Default", keyword="", name="now_time")
	#
	O_SHIKIGAMI_SKILL_1 = RuleOcr(roi=(1120,165,94,94), area=(1120,165,94,94), mode="Single", method="Default", keyword="", name="shikigami_skill_1")
	#
	O_SHIKIGAMI_SKILL_2 = RuleOcr(roi=(933,165,94,94), area=(933,165,94,94), mode="Single", method="Default", keyword="", name="shikigami_skill_2")
	#
	O_SHIKIGAMI_SKILL_3 = RuleOcr(roi=(746,165,94,94), area=(746,165,94,94), mode="Single", method="Default", keyword="", name="shikigami_skill_3")
	#
	O_SHIKIGAMI_SKILL_4 = RuleOcr(roi=(559,165,94,94), area=(559,165,94,94), mode="Single", method="Default", keyword="", name="shikigami_skill_4")
	#
	O_SHIKIGAMI_SKILL_5 = RuleOcr(roi=(372,165,94,94), area=(372,165,94,94), mode="Single", method="Default", keyword="", name="shikigami_skill_5")
	#
	O_RANK = RuleOcr(roi=(443,193,417,204), area=(443,193,417,204), mode="Single", method="Default", keyword="", name="rank")
	# 式神详情页名称
	O_SHIKIGAMI_SPECIFICS_NAME = RuleOcr(roi=(997,101,193,36), area=(997,101,193,36), mode="Single", method="Default", keyword="", name="shikigami_specifics_name")
	#
	O_SHIKIGAMI_NAME_1 = RuleOcr(roi=(1097,261,117,33), area=(1097,261,117,33), mode="Single", method="Default", keyword="", name="shikigami_name_1")
	#
	O_SHIKIGAMI_NAME_2 = RuleOcr(roi=(910,261,117,33), area=(910,261,117,33), mode="Single", method="Default", keyword="", name="shikigami_name_2")
	#
	O_SHIKIGAMI_NAME_3 = RuleOcr(roi=(723,261,117,33), area=(723,261,117,33), mode="Single", method="Default", keyword="", name="shikigami_name_3")
	#
	O_SHIKIGAMI_NAME_4 = RuleOcr(roi=(536,261,117,33), area=(536,261,117,33), mode="Single", method="Default", keyword="", name="shikigami_name_4")
	#
	O_SHIKIGAMI_NAME_5 = RuleOcr(roi=(349,261,117,33), area=(349,261,117,33), mode="Single", method="Default", keyword="", name="shikigami_name_5")
	#
	O_GRIGRI_OPTION_NAME_1 = RuleOcr(roi=(269,370,191,45), area=(269,370,191,45), mode="Single", method="Default", keyword="", name="grigri_option_name_1")
	#
	O_GRIGRI_OPTION_NAME_2 = RuleOcr(roi=(548,370,191,45), area=(548,370,191,45), mode="Single", method="Default", keyword="", name="grigri_option_name_2")
	#
	O_GRIGRI_OPTION_NAME_3 = RuleOcr(roi=(825,370,191,45), area=(825,370,191,45), mode="Single", method="Default", keyword="", name="grigri_option_name_3")
	#
	O_FREE_REFRESH_COUNT = RuleOcr(roi=(1183,392,38,24), area=(1183,392,38,24), mode="Digit", method="Default", keyword="", name="free_refresh_count")
